### 톰캣서버의 포트번호를 정의한다.
server:
  port: 80
### 로그 출력 레벨 설정하기
logging:
  level:
    '[com.example.demo.mapper]': trace
spring:
### 애플리케이션 이름을 정의한다.
  application:
    name: store
### 데이터베이스 연결정보를 정의한다.
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hta
    password: zxcv1234
### spring mvc 설정
  mvc:  # JSP 뷰페이지 경로 및 확장자를 정의한다.
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
### mybatis 설정
mybatis:
  mapper-locations: # 매퍼파일 저장경로를 정의한다.
    - mybatis/mappers/*.xml
  type-aliases-package: com.example.demo.vo
  configuration:  # 기타 설정정보를 정의한다.
    jdbc-type-for-null: NULL
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
### 첨부파일 업로드 폴더
upload:
  directory:
    board: "c:/files/board"